// Generated by https://quicktype.io

export interface Purchases {
    movieCard:        MovieCard;
    purchaseId:       number;
    userId:           number;
    purchaseNumber:   string;
    totalPrice:       number;
    purchaseDateTime: string;
}

export interface MovieCard {
    id:        number;
    title:     string;
    posterUrl: string;
}
